apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-sdk-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator-sdk-statefulset
  template:
    metadata:
      labels:
        name: operator-sdk-statefulset
    spec:
      serviceAccountName: operator-sdk-statefulset
      containers:
        - name: operator-sdk-statefulset
          # Replace this with the built image name
          image: registry.vizion.ai/library/test-operator-sts:v0.0.1
          command:
          - operator-sdk-statefulset
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator-sdk-statefulset"
